layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: linux_china
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Reactive/RSocket
    web_url: http://rsocket.io/
    image_url: https://avatars0.githubusercontent.com/u/25459855?s=200&v=4

  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://avatars2.githubusercontent.com/u/1446536?s=200&v=4

  - name: WebAssembly
    web_url: https://webassembly.org/
    image_url: https://avatars1.githubusercontent.com/u/11578470?s=200&v=4

  - name: Spring Projects
    web_url: https://spring.io/
    image_url: https://avatars0.githubusercontent.com/u/317776?s=200&v=4
